# 异常捕获机制

## 1. 基本语法

> C# 异常处理时建立在四个关键词 之上的：try、catch、finally 和 throw。
>
> 异常捕获结构可以是如下形式：
>
> * try{...} catch{...}
> * try{...} catch{....} catch{...}
> * try{...} catch{....} finally{...}
> * try{...} catch{....} catch{...} ... finally{...}
> * try{...} finally{...} //此结构一般用于资源释放。

**异常捕获标准处理结构：**

````c#
try
{
    //要检测异常的程序代码
}
catch(Execption e)
{
    Console.WriteLine("异常提示");
    //Log(e.Message) //打印异常日志
    throw e;//抛出异常，交由调用者去处理
}
finally
{
    //一定会处理的代码
}
````

## 2. 特点

* 当有多个 catch 结构时，大类异常要放在后面捕获，小类异常要放在前面捕获。
* finally{...} 结构中的代码一定会执行。
* 如果在 catch{...} 中，存在 return 语句，那么程序在执行时会先保存 return 值，再去执行 finally{...} 结构中的代码，finally{...} 结构中对 return 的变量修改是无效的，最终返回的还是原先预先保存好的 return 值。
* finally{...} 结构中不能使用 return 语句。

````c#
internal class Program
{
    static int b = 0;
    static void Main(string[] args)
    {
        Console.WriteLine(test());
        Console.WriteLine($"b值：{b}");
    }
    static int test()
    {
        int a = 0;
        try
        {
            a++;
            a++;
            a = b / 0;
            b = 2;
            return b;
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
            b = 20;
            return b;//执行到此时，会得出并保存return值为20,再去执行finally中的代码。
        }
        finally
        {
            //此处，对 b 值的修改是有效的，但是不会影响return值。
            //因为return值在执行catch代码时就已经确认好了。
            b = 100;
        }
    }
}
````

